### PR TITLE
docs: docs for some docless components

### PR DESCRIPTION
**Pull request by JoeDuncko**
## What is the problem?

Docs were missing for some components

## What changes does this PR make to fix the problem?

- [x] Docs for useMountEffect
- [x] Docs for useRerender
- [x] Docs for useToggle
- [x] Docs for useUnmountEffect

## Checklist

- [ ] Is there an existing issue for this PR?
  - _link issue here_

### CODE REVIEW

**Comment by JoeDuncko** [comment]
Question: Why is the `effect` of `useMountEffect` of type `CallableFunction` instead of `EffectCallback`?

**Comment by JoeDuncko** [comment]
@xobotyi Okay, I think I got them all. I'd definitely look over this as I'm not super familiar with Typescript. Feedback is appreciated!

**Comment by xobotyi** [comment]
> Question: Why is the `effect` of `useMountEffect` of type `CallableFunction` instead of `EffectCallback`?
> 

Because `EffectCallback` can be void or destructor type, while `useMountEffect` expecting any callable function with any return type.
For the case of destruction required developers expected to use `useEffect`

**Comment by JoeDuncko** [comment]
> > Question: Why is the `effect` of `useMountEffect` of type `CallableFunction` instead of `EffectCallback`?
> 
> Because `EffectCallback` can be void function or return destructor type, while `useMountEffect` expecting any callable function with any return type.
> For the case of destruction required developers expected to use `useEffect`.

Thanks!

**Pull request merged**
