### PR TITLE
feat: new hook `useMediaQuery`

### PR DESCRIPTION
**Pull request by xobotyi**
## What new hook does?

Tracks the state of CSS media query.

## Checklist

- [x] Have you read [contribution guideline](../../CONTRIBUTING.md)?
- [x] Does the code have comments in hard-to-understand areas?
- [x] Is there an existing issue for this PR?
  - #33 
- [x] Have the files been linted and formatted?
- [x] Have the docs been updated?
- [x] Have the tests been added to cover new hook?
- [x] Have you run the tests locally to confirm they pass?

### CODE REVIEW

**Review by JoeDuncko — COMMENTED** [review]
Question: I don't see any tests that cover when the user puts in invalid media queries. What happens when that's the case? I wonder if there is a better API we can have here to guide the user to write a correctly formatted media query and give better errors when a media query is malformed. What do you think?

**Comment by JoeDuncko** [comment]
However, it does seem to work, so I'm going to approve it.

**Review by JoeDuncko — APPROVED** [review]

**Comment by xobotyi** [comment]
@JoeDuncko ideally we can compare passed query and the one that returned in `MediaQueryList`, but it needs way deeper invesigation across browsers.

Ill merge it this way if question will rise anytime later we will do improvement pr.

**Pull request merged**
