### PR TITLE
fix the examples of useAsync

### PR DESCRIPTION
**Pull request by Rey-Wang**
## What is the problem?
`useAsync` gives wrong examples
## What changes does this PR make to fix the problem?
correct the example
## Checklist

- [x] Is there an existing issue for this PR?
  - fix: #343

### CODE REVIEW

**Comment by xobotyi** [comment]
Thanks!

**Comment by Rey-Wang** [comment]
@xobotyi I'm working for the lint errors, then I found you have already merged it...

**Comment by xobotyi** [comment]
I've noticed, preliminary merging didn't go well😅
Should have been waited ci end🤌🤦‍♂️

**Comment by xobotyi** [comment]
@Rey-Wang why you skipped git hooks though? Lining is included there🤔

**Comment by Rey-Wang** [comment]
@xobotyi because im the first contributer, so there need some one approve to run the ci,  could you help me fix the lint if you are conveinent?

**Comment by xobotyi** [comment]
@Rey-Wang git hooks are runnung on your machine, not in CI environment.

**Comment by Rey-Wang** [comment]
oh so its not the ci.. sorry im not familiar about that and i sitll trying to figure it out. did not realize that your feed back is so quick😂

**Pull request merged**
