### PR TITLE
docs: adds documentation on how to migrate from useSetState hook

### PR DESCRIPTION
**Pull request by punkle**
adds documentation on hot to migrate from useSetState hook

## Checklist

- [x] Have you read [contribution guideline](../../CONTRIBUTING.md)?
- [x] Does the code have comments in hard-to-understand areas?
- [x] Is there an existing issue for this PR?
  - #33
- [x] Have the files been linted and formatted?
- [x] Have the docs been updated?
- [ ] Have the tests been added to cover new hook?
- [x] Have you run the tests locally to confirm they pass?

### CODE REVIEW

**Comment by xobotyi** [comment]
@JoeDuncko should we even implement it? 

It is slightly shorter version of `setState((state)=>{...state, newItem})` and i dont see any need to make unnecessary(imho) wrapper.

**Comment by JoeDuncko** [comment]
@xobotyi Yeah, I agree. Considering this is a one liner otherwise, I don't see the value to adding it to `hookz`. I can be convinced though. Thoughts @punkle ?

I wonder if we should go through the `Not Yet Implemented` list and remove some. Normally 

That being said, thank you for your contribution @punkle . Even if we don't end up using it, I appreciate you making such a thorough PR. Like I said, I can definitely be convinced that this has value over `setState((state)=>{...state, newItem})`, I'm just not seeing it on first glance.

**Comment by punkle** [comment]
Hey. I am happy to leave it once it's possible somehow. I had been attempting to port a downstream project that was using this function. If you agree I'll reduce this change to documentation about how to migrate from using react-use useSetState.

**Comment by punkle** [comment]
Thanks for the comments, that's done.

**Pull request merged**
