### PR TITLE
feat: new hook `useTitle`

### PR DESCRIPTION
**Pull request by xobotyi**
## What new hook does?

Sets title of the page.

## Checklist

- [x] Have you read [contribution guideline](../../CONTRIBUTING.md)?
- [x] Does the code have comments in hard-to-understand areas?
- [x] Is there an existing issue for this PR?
  - #33 
- [x] Have the files been linted and formatted?
- [x] Have the docs been updated?
- [x] Have the tests been added to cover new hook?
- [x] Have you run the tests locally to confirm they pass?

### CODE REVIEW

**Review by JoeDuncko — COMMENTED** [review]
The example doesn't seem to be working for me
Screen Recording 2021-05-25 at 4 15 07 PM

**Comment by JoeDuncko** [comment]
Also, I think we should include a link to https://github.com/nfl/react-helmet in case they want to use something more powerful. Maybe we should come up with a formal way to include alternatives in our docs?

**Comment by xobotyi** [comment]
> The example doesn't seem to be working for me
> Screen Recording 2021-05-25 at 4 15 07 PM

It actually works, buuuut, the document page is inside iframe =\
Im digging into changing the docs generator to smth else.

**Comment by JoeDuncko** [comment]
That probably makes that a bad example lol. Anything we can do to make it better?

**Comment by xobotyi** [comment]
Nothing while using storybook, attempt to make it handle iframes will be quite bad idea, since react render flows are not aligned between parrent and child frame.

**Comment by xobotyi** [comment]
@JoeDuncko added notification about not working story.

**Comment by septs** [comment]
i want's the hook can rename to `useDocumentTitle`, thanks

**Comment by xobotyi** [comment]
Actually this is a good idea

**Pull request merged**
