### PR TITLE
feat: new hook `useMap`

### PR DESCRIPTION
**Pull request by xobotyi**
## What new hook does?

Tracks the state of a `Map`.

## Checklist

- [x] Have you read [contribution guideline](../../CONTRIBUTING.md)?
- [x] Does the code have comments in hard-to-understand areas?
- [x] Is there an existing issue for this PR?
  - #33
- [x] Have the files been linted and formatted?
- [x] Have the docs been updated?
- [x] Have the tests been added to cover new hook?
- [x] Have you run the tests locally to confirm they pass?

### CODE REVIEW

**Review by JoeDuncko — APPROVED** [review]
LGTM

**Comment by DanHarman** [comment]
I don't understand why this has a mutable object api in contrast to useList which returns the operations distinct to the list. This makes the library inconsistent?

**Comment by xobotyi** [comment]
1) Сopying a map of 1k numbers is two orders of magnitude slower than copying same size array (like it is slow af).
2) There is no way of giving an access to a map without making it mutable, `Map` method mutates its source and there is nothing to do with it.

**Comment by DanHarman** [comment]
Understood. I wonder if it would be better to return the proxied apis in the way list does, although then risk of people mutating the map directly without the proxied versions unless they are removed from the returned map. All quite difficult trade offs so I understand your decision now.

**Comment by DanHarman** [comment]
Understood. I wonder if it would be better to return the proxied apis in the way list does, although then risk of people mutating the map directly without the proxied versions unless they are removed from the returned map. All quite difficult trade offs so I understand your decision now.

**Pull request merged**
