### PR TITLE
feat: new hook useIsMounted

### PR DESCRIPTION
**Pull request by xobotyi**
## What new hook does?

Returns function that yields current mount state.

## Checklist

- [x] Have you read [contribution guideline](../../CONTRIBUTING.md)?
- [x] Does the code have comments in hard-to-understand areas?
- [ ] Is there an existing issue for this PR?
  - _link issue here_
- [x] Have the files been linted and formatted?
- [x] Have the docs been updated?
- [x] Have the tests been added to cover new hook?
- [x] Have you run the tests locally to confirm they pass?

### CODE REVIEW

**Comment by JoeDuncko** [comment]
It looks like this is supposed to be equivalent to react-use's ` useMountedState`. 

I'm not sure how I feel about this implementation. 
- Why not include the word `state` in the name? I think emulating something like `recoil`'s `useRecoilVallue` here... Maybe in that case this should be `useMountedValue`? Either way, not a big fan of using `getter` here - not very react-y IMO.
- Why does this return a function instead of a value?

**Comment by xobotyi** [comment]
1. It is not a state, it is, as said, getter - hook reruns a function that yield component's mount state. I've named it incorrectly in `use-hooks`, people was confused sometimes. 
2. It is required mostly for async effects, as conventional state change unable to take effect over already triggered request callbacks. Thus we need kind of ref, but writing each time `isMounted.current` not handy.

**Comment by xobotyi** [comment]
@JoeDuncko what i am thinking of is to rename it to `useIsMounted`

**Comment by JoeDuncko** [comment]
1. understood
2. that makes sense

I definitely like `useIsMounted` more. Let's do that.

**Comment by xobotyi** [comment]
@JoeDuncko otherwise fine? merge?

**Comment by JoeDuncko** [comment]
Let me test the example, then I'll merge...

**Comment by JoeDuncko** [comment]
```
Child HtmlWebpackCompiler:
                          Asset      Size               Chunks  Chunk Names
    __child-HtmlWebpackPlugin_0  6.23 KiB  HtmlWebpackPlugin_0  HtmlWebpackPlugin_0
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    [./node_modules/html-webpack-plugin/lib/loader.js!./node_modules/@storybook/core-common/dist/cjs/templates/index.ejs] 1.98 KiB {HtmlWebpackPlugin_0} [built]
ModuleNotFoundError: Module not found: Error: Can't resolve './useMountedGetter.stories' in '/Users/joeduncko/Documents/GitHub/web/stories'
```

**Comment by xobotyi** [comment]
Aha, somehy not renamed during files renaming.

**Review by JoeDuncko — APPROVED** [review]
LGTM

**Pull request merged**
