### PR TITLE
docs(useDefault): Suggest `useMediatedState` instead 

### PR DESCRIPTION
**Pull request by AndreasNel**
## What new hook does?

It works like `useSafeState`, except it will return the provided default value when the state is set to `undefined` or `null`.

## Checklist

- [x] Have you read [contribution guideline](../../CONTRIBUTING.md)?
- [x] Does the code have comments in hard-to-understand areas?
- [x] Is there an existing issue for this PR?
  - #33 
- [x] Have the files been linted and formatted?
- [x] Have the docs been updated?
- [x] Have the tests been added to cover new hook?
- [x] Have you run the tests locally to confirm they pass?

### CODE REVIEW

**Comment by xobotyi** [comment]
TBH i dont think we need that hook since it is easily (and versatile) achievable via `useMediatedState` hook.

@JoeDuncko WDYT?

**Comment by JoeDuncko** [comment]
I wonder if we should have a cookbook of common hooks that can be easily derived from our hooks, or something like that.

Maybe as examples in Storybook?

I know that doesn't exactly answer the question though.

**Comment by xobotyi** [comment]
I've been thinking about that too (cookbook). Maybe separte page near migration and reference in mugration like `we dont have this hook implemented directly as it can be easily achieved via other hook, and here is example link.`

**Comment by JoeDuncko** [comment]
> Yeah a cookbook sounds good, do you want me to create such a page? Or would you prefer doing it?

Sorry for the slow reply. If you know your way around Storybook, go for it! I'm still new to Storybook, so I'd have to figure out the best way to present alternative examples. Ideas welcome.

**Comment by AndreasNel** [comment]
Apologies for leaving this for so long, life kind of got in the way and this got away from me. Please check if the documentation suggestion is correct.

**Comment by xobotyi** [comment]
LGTM, merging after all check passed.

**Pull request merged**
